Major update to our CVS admin scripts (*gulp*).  We're now much closer to using the stock FreeBSD versions so that future upgrades will be easier.
git-svn-id: https://vrjuggler.googlecode.com/svn/trunk@7328 08b38cba-cd3b-11de-854e-f91c5b6e4272

diff --git a/CVSROOT/commitcheck b/CVSROOT/commitcheck
--- a/CVSROOT/commitcheck
+++ b/CVSROOT/commitcheck
@@ -1,36 +1,74 @@
-#! /bin/sh
+#!/usr/bin/perl -w
 #
-# $FreeBSD: CVSROOT/commitcheck,v 1.12 1999/09/19 13:11:03 peter Exp $
-# $Id$$
+# $FreeBSD: CVSROOT/commitcheck,v 1.23 2001/11/15 13:09:58 joe Exp $
 
 #
-# BEWARE:  If you are "borrowing" this code for use on another cvs
-# repository, please make sure you change all references to '@FreeBSD.org'
-# in the log_accum script.  Otherwise your commit messages will be sent
-# to 'cvs-committers@freebsd.org' etc.  This could be highly embarresing. :-)
+# This script is the first thing that is run at commit time
+# to determine whether the committer has commit priviledges.
+# (See CVSROOT/commitinfo).
 #
+
+use strict;
+use lib $ENV{CVSROOT};
+use CVSROOT::cfg;
+my $CVSROOT = $ENV{CVSROOT} || die "Can't determine CVSROOT (commitcheck)!\n";
+
+
+# Check that the user is committing on the right machine.
+#
+use Sys::Hostname;
+my $hostname = hostname();
+if (@cfg::COMMIT_HOSTS && !grep(/^\Q$hostname\E$/i, @cfg::COMMIT_HOSTS)) {
+	print "Please don't commit on this host!\n";
+	print "Please commit on ",
+	    join(" or ", @cfg::COMMIT_HOSTS),
+	    " instead.\n";
+	exit 1;
+}
+
+
+# Run locally defined extra commitchecks.
+if (defined($cfg::COMMITCHECK_EXTRA) && $cfg::COMMITCHECK_EXTRA) {
+	die 'commitcheck: $cfg::COMMITCHECK_EXTRA isn\'t a sub!'
+	    unless ref($cfg::COMMITCHECK_EXTRA) eq "CODE";
+
+	die "Failed commitcheck_extra\n" unless &$cfg::COMMITCHECK_EXTRA();
+}
+
+
+#
+# Ensure the minimum version of cvs is installed.
+#
+my $VERSTR = `$cfg::PROG_CVS -v`;
+$VERSTR =~ s/.*Concurrent\D*(\S*).*/$1/s;
+$VERSTR =~ s/\D+/./g;
+my $VERSION = sprintf "%d%02d%02d%02d\n", split /\./, $VERSTR;
+unless ($VERSION && $VERSION >= $cfg::MINCVSVERSION) {
+	print "The wrong version of CVS is installed (commitcheck)!\n";
+	exit 1;
+}
+
 
 #
 # Does the access control list allow them commit access?
 #
-#if $CVSROOT/CVSROOT/cvs_acls.pl ${1+"$@"}
-#then
-#	:	# OK
-#else
-#	echo "Access control checks failed! (cvs_acls.pl)" 1>&2
-#	exit 1
-#fi
+#system("$CVSROOT/CVSROOT/cvs_acls.pl", @ARGV);
+#if ($? >> 8) {
+#	print "Access control checks failed! (cvs_acls.pl)\n";
+#	exit 1;
+#}
 
 #
-# Last minute checks and preperations for log_accum.pl later.  This
+# Last minute checks and preparations for log_accum.pl later.  This
 # records the last directory in this commit so that log_accum knows when
 # to finish coalescing commit messages and mail it.
 #
-if $CVSROOT/CVSROOT/commit_prep.pl ${1+"$@"}
-then
-	:	# OK
-else
-	echo "commit_prep.pl failed!" 1>&2
-fi
+system("$CVSROOT/CVSROOT/commit_prep.pl", @ARGV);
+if ($? >> 8) {
+	print "commit_prep.pl failed!\n";
+	exit 1;
+}
 
-exit 0		# Lets do it!
+exit 0;		# Lets do it!
+
+#end
