Extended the behavior of the last commit.  If JDK_HOME is not set, it defaults to /usr/java, and a warning is printed stating that this is being done.  If $JDK_HOME/bin/java cannot be executed, an error is printed saying so instead of just trying to start up VjControl and being hopeful that $JDK_HOME/bin/java will be there.  The end result should be that users will notice that they don't have JDK_HOME set properly and will fix their environment variables.
    Suggested by: "jan p. springer" <jsd@igroup.org>


git-svn-id: https://vrjuggler.googlecode.com/svn/trunk@2680 08b38cba-cd3b-11de-854e-f91c5b6e4272

diff --git a/juggler_1.0/GUI/vjcontrol b/juggler_1.0/GUI/vjcontrol
--- a/juggler_1.0/GUI/vjcontrol
+++ b/juggler_1.0/GUI/vjcontrol
@@ -2,5 +2,23 @@
 
 # shell script for running vjcontrol under jdk 1.2 using the java command
 
-CLASSPATH=
-${JDK_HOME-/usr/java}/bin/java -DVJ_BASE_DIR=${VJ_BASE_DIR} -cp ${VJ_BASE_DIR}/bin/VjControl.jar VjGUI.VjControl $*
+# If the environment variable JDK_HOME is not set, default it to /usr/java.
+if test "x${JDK_HOME}" = "x" ; then
+    echo "WARNING: Setting JDK_HOME environment variable to /usr/java"
+    JDK_HOME='/usr/java' ; export JDK_HOME
+fi
+
+# Make sure that $JDK_HOME/bin/java exists and is executable.  If it is not,
+# exit with an error message and status 1.
+if test ! -x "$JDK_HOME/bin/java" ; then
+    echo "ERROR: Could not find Java in $JDK_HOME"
+    status=1
+# Otherwise, start up VjControl and exit with status 0.
+else
+    CLASSPATH=
+    ${JDK_HOME}/bin/java -DVJ_BASE_DIR=${VJ_BASE_DIR} -cp	\
+      ${VJ_BASE_DIR}/bin/VjControl.jar VjGUI.VjControl $*
+    status=0
+fi
+
+exit $status
