Exit with error status if JAVA_HOME is not set.
git-svn-id: https://vrjuggler.googlecode.com/svn/trunk@15743 08b38cba-cd3b-11de-854e-f91c5b6e4272

diff --git a/juggler/external/JacORB/idl b/juggler/external/JacORB/idl
--- a/juggler/external/JacORB/idl
+++ b/juggler/external/JacORB/idl
@@ -2,6 +2,11 @@
 
 : ${JACORB_PATH=.}
 
+if test "x$JAVA_HOME" = "x" ; then
+   echo "ERROR: JAVA_HOME environment variable not set!"
+   exit 1
+fi
+
 # Converts path to a Win32 style path if we're in Cygwin
 fixpath()
 {
